spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///pethome
    username: root
    password: 123456

mybatis:
  type-aliases-package: cn.xavier.org.domain,cn.xavier.org.query

logging:
  file: logs/application-debug.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: error
    cn.xavier: trace