spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///pethome
    username: root
    password: 123456
  mail:
    host: smtp.yeah.net
    username: shuizhengwei@yeah.net
    password: ROZZDXKOPLOISFRJ
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456
    jedis:
      pool:
        max-wait: 2000ms
        min-idle: 0
        max-idle: 8
        max-active: 20

mybatis:
  type-aliases-package: cn.xavier.org.domain,cn.xavier.org.query,
                        cn.xavier.system.domain,cn.xavier.system.query
                        cn.xavier.user.domain,cn.xavier.user.query
                        cn.xavier.basic.domain,cn.xavier.basic.query
                        cn.xavier.pet.domain,cn.xavier.pet.query
                        cn.xavier.order.domain,cn.xavier.order.query
                        cn.xavier.pay.domain,cn.xavier.pay.query

logging:
  file: logs/application-debug.log
  pattern:
    console: "%d %-5level %logger %X{requestId}: %msg%n"
    file: "%d %-5level [%thread] %logger %X{requestId}: %msg%n"
  level:
    org.springframework.web: error
    cn.xavier: trace

# 查看Spring Boot自动配置类生效情况
debug: true

# 订单超时时间
order:
  timeout:
    minutes: 15